spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET
            series: SERVER-ERROR
            backoff:
              firstBackoff: 50ms
              maxBackoff: 100ms
              basedOnPreviousValue: false
              factor: 2
      routes:
        - id: message-route
          uri: lb://SERVER-MESSAGE/message
          predicates:
            - Path=/message/
        - id: user-route
          uri: lb://USER-SERVER/user
          predicates:
            - Path=/user/
        - id: lib-route
          uri: lb://LIB-SERVER/lib
          predicates:
            - Path=/lib/
    loadbalancer:
      ribbon:
        enabled: 'false'

eureka:
  instance:
    preferIpAddress: 'true'
  client:
    fetchRegistry: 'true'
    registerWithEureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoint:
    gateway:
      enabled: true
  health:
    show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
