spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'
    loadbalancer:
      ribbon:
        enabled: 'false'
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    preferIpAddress: 'true'
  client:
    fetchRegistry: 'true'
    registerWithEureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
