spring:
  data:
    mongodb:
      uri:  mongodb://localhost:27017/admin
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    fetchRegistry: 'true'
    registerWithEureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761

