resilience4j.circuitbreaker:
    instances:
      circuitBreakerService:
        ringBufferSizeInHalfOpenState: 5
        ringBufferSizeInClosedState: 5
        failureRateThreshold: 50
        registerHealthIndicator: true
        waitDurationInOpenState: 5s
        recordExceptions:
          - java.lang.RuntimeException
          - java.io.IOException

resilience4j.retry:
  instances:
    retryService:
      maxAttempts: 5
      waitDuration: 10s
      retryExceptions:
        - java.util.concurrent.TimeoutException
        - java.net.ConnectException

      
eureka:
  instance:
    preferIpAddress: 'true'
  client:
    fetchRegistry: 'true'
    registerWithEureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: 'false'
        
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/server_user
    password: postgres

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
